CartoDB/observatory-extension

src/pg/test/expected/41_observatory_augmentation_test.out, src/pg/test/sql/41_observatory_augmentation_test.sql
This PR updates tests in 41 to check if 
* numeric values are within 0.1% of expected value, and 
* checks individual key/value pairs in JSON responses instead of raw JSON which could have a different ordering of keys
closes #51 
cc @iriberri
=> update tests to account for json responses with different key orders and

scripts/README.md, scripts/autotest.py
If you want to simplify the automated testing regimen, you may want to cherry-pick this @ethervoid .
=> simpler access to metadata via observatory.cartodb.com

NEWS.md, src/pg/observatory.control
@ethervoid, updating version to 0.0.5 here. This includes the new function `OBS_GetMeasureById` from #96.
=> updating version to 0.0.5

scripts/autotest.py
Could you review @ohasselblad ? I added a lot of geom tests, but I think it's overkill to test every function against every measure, so left them commented out for now.  The exception are the `getuscensusmeasure` tests, which work more directly with metadata and are at risk of partially breaking.
I didn't update the control version as I don't think doing a new deploy for this is essential, just should have it in `develop`.
=> add getuscensusmeasure tests, and (commented out) additional geom tests

scripts/generate_fixtures.py, src/pg/sql/40_observatory_utility.sql, src/pg/test/expected/40_observatory_utility_test.out, src/pg/test/fixtures/drop_fixtures.sql, src/pg/test/sql/40_observatory_utility_test.sql
Resolves #114 .
Chose to just test returns NOT NULL because every time we update fixtures the dump version is liable to change.
@ohasselblad CR please?  Opened a blank release-v-0.0.6 branch so that we have a clean PR when we decide to deploy.
=> Obs dump version

scripts/autotest.py, src/pg/sql/41_observatory_augmentation.sql
Also enables our `obsgetmeasure_area` tests, so this can't creep up on us again in the future!
Resolves https://github.com/CartoDB/observatory-extension/issues/121 .
All tests pass on envisage, plus the UK area tests now pass.  Can you take a quick look @ohasselblad ? Would like to get this rolled up into our next release with the other outstanding PRs ASAP.
=> Geom_ref colname from geom table used with data table, too

NEWS.md, scripts/autotest.py, scripts/generate_fixtures.py, src/pg/observatory.control, src/pg/sql/40_observatory_utility.sql, src/pg/sql/41_observatory_augmentation.sql, src/pg/sql/42_observatory_exploration.sql, src/pg/test/expected/40_observatory_utility_test.out, src/pg/test/fixtures/drop_fixtures.sql, src/pg/test/sql/40_observatory_utility_test.sql
@ethervoid this should be good to go.  Currently we have a bug blocking full use of UK data, so would be good to get it out ASAP.
A word on the version change -- this does *not* include breaking changes with prior versions, so no worries there.  It's just that 0.x.x releases should a) be reserved only for pre-production (which we're not) and b) are prohibited in SemVer 2.  So I'm taking the opportunity to boost us to 1.0.0 status.
Technically, this would be a minor version change, since we're adding a new function but not breaking any backwards compatbility.
=> Release v 1.0.0

src/pg/sql/42_observatory_exploration.sql
Should resolve obs_getavailableboundaries mixed SRID complaint on staging found in https://github.com/CartoDB/observatory-extension/issues/129 .
If this looks good as an approach (the more long-lasting fix is to define an SRID for obs_table) then I will bump the control to 1.0.1.
=> preemptively set_srid for obs_getavailableboundaries

scripts/generate_fixtures.py, src/pg/sql/41_observatory_augmentation.sql, src/pg/test/expected/41_observatory_augmentation_test.out, src/pg/test/expected/42_observatory_exploration_test.out, src/pg/test/expected/44_observatory_geometries_test.out, src/pg/test/fixtures/drop_fixtures.sql, src/pg/test/sql/40_observatory_utility_test.sql, src/pg/test/sql/41_observatory_augmentation_test.sql, src/pg/test/sql/42_observatory_exploration_test.sql, src/pg/test/sql/44_observatory_geometries_test.sql
* Supports use of `obs_meta` table in our unit tests
- Since this table is too big to save as a fixture, it has to be regenerated -- this is a bit slow, so tests were changed to not drop/create tables between files.  That should be safe because we only `SELECT` in our tests, and we should never alter the fixture data
* Use `obs_meta` table for `OBS_GetMeasureByID`
- This should result in major performance improvements, saw a factor of ~2.5 on our test setup (which uses FDW)
=> Use obs_meta for OBS_GetMeasureByID, support obs_meta

src/pg/sql/41_observatory_augmentation.sql, src/pg/test/expected/41_observatory_augmentation_test.out, src/pg/test/sql/41_observatory_augmentation_test.sql
* Handle mixed geometries (IE one column with ZCTA data, another with tract data) far more efficiently
- Instead of matching all user geometries to all Observatory geometries in one CTE, we now do one CTE per unique Observatory geometry
* Automatically assign `normalization` as part of `OBS_GetMeta` when it is not specified.
=> Handle mixed geometries

src/pg/sql/41_observatory_augmentation.sql, src/pg/test/expected/41_observatory_augmentation_test.out, src/pg/test/sql/41_observatory_augmentation_test.sql
I'd like to request a new data observatory extension deploy: dump + extension
Performance is identical to 1.5.0, except for regression in `OBS_GetCategory`.  However, `OBS_GetCategory` performance is not a priority as it should only be used on one-off requests for data.  Bulk requests should be handled through `OBS_GetData`.
Please put here the dump id to be deployed: `Dump_2017_05_04_f20ee1131c.dump`
- https://github.com/CartoDB/observatory-extension/pull/285
=> Release v1.5.1

src/pg/sql/41_observatory_augmentation.sql
Right now we're doing INNER JOINS when we JOIN the _procgeoms and
the data so we end up with NULL value instead of id, NULL value. We need
to have the id available to make the JOIN at the end of the query and
provide results like this:
```
id |                               data
----+------------------------------------------------------------------
1 | [{"value" : 858469},{"value" : 73.9397964478},{"value" : 69092}]
2 | [{"value" : 738774},{"value" : null},{"value" : 2235406}]
```
// @juanignaciosl for awareness
=> Return NULL for the affected value and not for all the measurements

src/pg/sql/42_observatory_exploration.sql, src/pg/test/expected/42_observatory_exploration_test.out, src/pg/test/sql/42_observatory_exploration_test.sql
The current OBS_GetAvailableNumerators is not designed with our
UI in mind so it's causing a lot of troubles and we're doing so
many hacks to fit our UI needs and the interface of the function so this
function it's a better fit for our purposes.
This function is private because, by now, we don't want to expose
as a public function because could suffer changes in the near future.
=> New private function _OBS_GetNumerators to be used in our UI

src/python/test/autotest.py
#307 
- Group tests based on the test point rather than by numerator.
- Added default point for the `us.census.tiger.school_district_elementary_geoname` and `us.census.tiger.school_district_secondary_geoname` columns.
- Skipped Eurostat from the tests.
- Refactoring.
=> 307 tests for different points fixed

.travis.yml, src/python/test/perftest.py
This is needed for tests to pass since we don't have WOF in our current dump
=> Remove WOF perftests. 

doc/discovery_functions.md, src/pg/observatory.control, src/pg/sql/42_observatory_exploration.sql
We need the number of geometries to pass them to the get score function
in order to get an accurate score for the input in order to suggest
what is the geometry that fits better for the input we have
=> OBS_GetAvailableGeometries now receives number of geometries from input

src/pg/sql/41_observatory_augmentation.sql, src/pg/test/sql/41_observatory_augmentation_test.sql
Modified the `suggested_name` for denominator normalizations to mitigate collisions between column names: `numerator_timespan_by_denominator`.
This mitigates the problem but doesn't completely solve it because the `suggested_name` can easily reach the 63 character limitation for the column names.
Fixes https://github.com/CartoDB/cartoframes/issues/323
=> Modified the denominated suggested_name to mitigate collisions

release/observatory--1.9.0.sql, src/pg/sql/42_observatory_exploration.sql
We have two options for this change:
a) Go with the new fields which imply to deploy [dataservices](https://github.com/CartoDB/dataservices-api/pull/493) and a non-graceful deploy because we have some time between the new DS version is deployed and we change the config to point to the new  obs dump. Also this leads to put the dump directly into production
b) Remove this new fields, which are not going to be used at the moment and make only a release for observatory.
I've made the two PR
=> Remove new fields not used to simplify deploy process

.travis.yml, scripts/ci/install_postgres.sh, src/pg/sql/45_observatory_mvt.sql, src/pg/test/expected/01_install_test.out, src/pg/test/sql/01_install_test.sql
Added table to cache `OBS_GetMeta` function results and improve performance.
Although the `OBS_GetMeta` function receives the `geom` as a parameter, the cache is maintained for each zoom level.
Closes https://github.com/CartoDB/observatory-extension/issues/336
=> Added cache for OBS_GetMeta function results

.travis.yml, scripts/ci/docker-test.sh, scripts/ci/run_tests_docker.sh, src/pg/test/expected/42_observatory_exploration_test.out
- Start using Docker to test in TravisCI
- Support for PG10 and PG11 and remove support for old versions
=> Support for PG11

docs/guides/01-overview.md
I've been looking into the docs & noticed a broken link.
BTW what's the deal with having this stuff on master and not on develop? It looks like the branches have diverged
=> Fix broken link in docs
