CartoDB/observatory-extension

- CONTRIBUTING.md
- README.md
- RELEASE.md
@iriberri quick review, please?
> Develop doc fixes

- .gitignore
- src/pg/test/expected/01_install_test.out
- src/pg/test/sql/01_install_test.sql
@jgoizueta can you please review?
> Extension scaffolding fixes

- src/pg/sql/40_observatory_utility.sql
- src/pg/test/expected/40_observatory_utility_test.out
- src/pg/test/sql/40_observatory_utility_test.sql
> adding _OBS_GetRelatedColumn function

- src/pg/sql/40_observatory_utility.sql
- src/pg/sql/41_observatory_augmentation.sql
- src/pg/test/expected/40_observatory_utility_test.out
- src/pg/test/expected/41_observatory_augmentation_test.out
- src/pg/test/sql/40_observatory_utility_test.sql
- src/pg/test/sql/41_observatory_augmentation_test.sql
> Kill get census

- doc/methods.md
- src/pg/sql/40_observatory_utility.sql
- src/pg/sql/41_observatory_augmentation.sql
- src/pg/sql/42_observatory_exploration.sql
- src/pg/sql/44_observatory_geometries.sql
Reconciles docs with functions, adds schema to all functions, gives geometries srid, etc.
closes #52 
cc @iriberri
> Iss52 metaissue updates

- src/pg/sql/42_observatory_exploration.sql
Ref #52
@stuartlynn, could you double check that this works as expected?
cc @iriberri
> fixes timespan mis-naming issue

- src/pg/sql/44_observatory_geometries.sql
> remove hard-coded geoid from getgeometryid

- scripts/generate_fixtures.py
> adds fixture gen script

- src/pg/sql/44_observatory_geometries.sql
@talos, I simplified functions and used appropriate string operators everywhere. Take a look please.
> using appropriate operators in format function

- src/pg/sql/44_observatory_geometries.sql
> cast returned values to text

- src/pg/sql/42_observatory_exploration.sql
> casting to text, fixing return catch

- src/pg/sql/42_observatory_exploration.sql
> casting return types to text

- doc/API.md
- doc/boundary_functions.md
- doc/discovery_functions.md
- doc/glossary.md
- doc/license.md
- doc/measures_functions.md
@andrewxhill , as requested, a placeholder topic for the licensing information. 
Let me know if you need help with any content or editing?  Otherwise, ping me when completed and merged and I'll modify the Docs build structure to pull this in staging.
> added new doc topic, license

- doc/boundary_functions.md
- doc/measures_functions.md
@andrewxhill , permission to merge?
> added hyperlinks to best practices section

- doc/license.md
For [Docs issue#835](https://github.com/CartoDB/docs/issues/835). @vhamer, please approve and I'll merge.
> update license docs, per vhamer's request

- release/observatory.control
@ethervoid This release should fix the issues you saw on Tuesday that were blocking deploy of the new metadata.
> Fix broken getuscensusmeasure tag

- doc/license.md
Fixes #101 ,
@andrewxhill, please review and let me know if this is what you had in mind?
> updated license INE description

- NEWS.md
- doc/license.md
- doc/measures_functions.md
- src/pg/observatory.control
- src/pg/sql/41_observatory_augmentation.sql
- src/pg/test/expected/41_observatory_augmentation_test.out
- src/pg/test/sql/41_observatory_augmentation_test.sql
- Adds new function `OBS_GetMeasureById` ([#96](https://github.com/CartoDB/observatory-extension/pull/96))
> Version 0.0.5

- src/pg/sql/42_observatory_exploration.sql
Addresses #116, replaces #117.
@ohasselblad CR please?
> Use the geom instead of bounds

- doc/API.md
- doc/glossary.md
- doc/license.md
- doc/measures_functions.md
For [Docs issue#879](https://github.com/CartoDB/docs/issues/879)
@vhamer , please approve.
@talos , I've updated the license content as described in the attached issue. The DO PDF link contains a license page that is slightly different then the public docs page. I just want to make sure we're using one golden source for the content.
> modified license content as per Operations request

- doc/boundary_functions.md
- doc/discovery_functions.md
- doc/measures_functions.md
> rebranding

- scripts/autotest.py
This simply adds a location to test against for Mexico data in our end-to-end tests.
> test location for MX

- src/pg/sql/41_observatory_augmentation.sql
- src/pg/sql/44_observatory_geometries.sql
@ohasselblad Another one to CR
> comment out notices

- src/pg/sql/41_observatory_augmentation.sql
- src/pg/test/sql/41_observatory_augmentation_test.sql
@ohasselblad this is a clean PR, could you please CR?
> Fix hardcoded getcategory geom

- src/pg/sql/42_observatory_exploration.sql
**Needs new dump (2017_07_06_dd477a33f0) with the table `obs_meta_geom_numer_timespan** ([PR](https://github.com/CartoDB/bigmetadata/pull/190))
Now use the new meta table `obs_meta_geom_numer_timespan` to filter
the geometries by geometries timespan and/or numerator timespan (which
is what we get when we use the obs_getavailabletimespans)
> Modified OBS_GetAvailableGeometries

- .travis.yml
- scripts/generate_fixtures.py
- scripts/requirements.txt
- src/pg/sql/41_observatory_augmentation.sql
- src/pg/test/expected/41_observatory_augmentation_test.out
- src/pg/test/fixtures/drop_fixtures.sql
- src/pg/test/sql/41_observatory_augmentation_test.sql
New function to check the metadata in order to search for errors like
for example, if we have the metadata for a median aggregation and the
normalization is by are it'll fail.
> OBS_MetadataValidation

- doc/measures_functions.md
Doc for the new obs_metadatavalidation function
> OBS_MetadataValidation doc

- doc/discovery_functions.md
@ethervoid , looks good! I just rewrote the English a bit. Let me know if this is okay then we can update all the live docs.
> edited description in line 245

- doc/discovery_functions.md
> Remove cdb_observatory references

- .travis.yml
- scripts/ci/install_postgres.sh
- src/pg/test/sql/44_observatory_geometries_test.sql
> Postgresql 10 support

- CONTRIBUTING.md
- NEWS.md
- src/pg/observatory.control
- src/pg/sql/42_observatory_exploration.sql
- Refactor `OBS_GetAvailableTimespans`
- Updated documentation
Closes https://github.com/CartoDB/bigmetadata/issues/422
> Refactor OBS_GetAvailableTimespans

- src/pg/sql/45_observatory_mvt.sql
Added multi category support for the `OBS_GetMCDOMVT` function
Closes https://github.com/CartoDB/bigmetadata/issues/516
Closes https://github.com/CartoDB/observatory-extension/issues/339
Closes https://github.com/CartoDB/bigmetadata/issues/518
Closes https://github.com/CartoDB/observatory-extension/issues/341
> OBS_GetMCDOMVT can receive several categories

- src/pg/sql/45_observatory_mvt.sql
Improved query performance by removing outer joins, using the new MC tables
Related to https://github.com/CartoDB/bigmetadata/pull/532
> Improved query performance removing outer joins

- src/pg/sql/45_observatory_mvt.sql
Created a new GetDOMCMVT function that takes a zoom level and returns a table with all the XYZ/measurements
https://github.com/CartoDB/observatory-extension/issues/342
> New function to return the whole table from a zoom level/geography

- .travis.yml
- NEWS.md
- scripts/ci/install_postgres.sh
- src/pg/sql/45_observatory_mvt.sql
- src/pg/test/expected/01_install_test.out
- src/pg/test/sql/01_install_test.sql
Creating an MVT returning function for DO
Closes #333
> Created MVT returning function for DO

- src/pg/sql/45_observatory_mvt.sql
Changed MC schema from `tiler`
https://github.com/CartoDB/bigmetadata/issues/536
> Change MC schema

- src/pg/sql/45_observatory_mvt.sql
> Changed tiler schema name

- src/pg/sql/45_observatory_mvt.sql
> Fixed table naming

- src/pg/sql/45_observatory_mvt.sql
> Fix whole file date query

- carto-package.json
```
{
"observatory-server-extension": {
"repo_url": "https://github.com/CartoDB/observatory-extension.git",
"tag_format": "{VERSION}",
"manifest": "carto-package.json"
}
},
```
@lekum :eyes:
> carto-package.json
